//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostShop()
        {
            this.PostShopPay = new HashSet<PostShopPay>();
        }
    
        public int PostNumber { get; set; }
        public string PostName { get; set; }
        public string PostDistrict { get; set; }
        public string PostAdress { get; set; }
        public string PostTime { get; set; }
        public string PostPhone { get; set; }
        public string PostWeb { get; set; }
        public Nullable<bool> PostOutlet { get; set; }
        public Nullable<bool> PostWifi { get; set; }
        public Nullable<bool> PostLimitedTime { get; set; }
        public Nullable<bool> PostOrder { get; set; }
        public int UserNumber { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> PassDate { get; set; }
        public Nullable<int> AdmNumber { get; set; }
    
        public virtual Adm Adm { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostShopPay> PostShopPay { get; set; }
    }
}
