//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ShopPay
    {
        [DisplayName("店家付款方式編號")]
        public int Number { get; set; }

        [DisplayName("店家")]
        public int ShopNumber { get; set; }

        [DisplayName("付款方式")]
        [Required(ErrorMessage = "請選擇付款方式")]
        public int PayNumber { get; set; }

        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Pay Pay { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
