//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.ShopImage = new HashSet<ShopImage>();
            this.ShopMenu = new HashSet<ShopMenu>();
            this.ShopPay = new HashSet<ShopPay>();
            this.ShopTag = new HashSet<ShopTag>();
        }

        [DisplayName("店家編號")]
        public int ShopNumber { get; set; }

        [DisplayName("店家名稱")]
        [Required(ErrorMessage = "請填寫店家名稱")]
        public string ShopName { get; set; }

        [DisplayName("區域")]
        public string District { get; set; }

        [DisplayName("地址")]
        public string ShopAddress { get; set; }

        [DisplayName("營業時間")]
        public string ShopTime { get; set; }

        [DisplayName("電話")]
        public string Phone { get; set; }

        [DisplayName("網站")]
        public string Web { get; set; }

        [DisplayName("有插座")]
        public Nullable<bool> Outlet { get; set; }

        [DisplayName("有Wifi")]
        public Nullable<bool> WIFI { get; set; }

        [DisplayName("限時間")]
        public Nullable<bool> LimitedTime { get; set; }

        [DisplayName("可訂位")]
        public Nullable<bool> IsOrder { get; set; }

        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ShopDate { get; set; }

        [DisplayName("更新日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> UpdateDate { get; set; }

        [DisplayName("管理員")]
        public int AdmNumber { get; set; }

        [DisplayName("已歇業")]
        [DefaultValue(false)]
        public Nullable<bool> Closed { get; set; }
    
        public virtual Adm Adm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopImage> ShopImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopMenu> ShopMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopPay> ShopPay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopTag> ShopTag { get; set; }
    }
}
