//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopPay
    {
        public int Number { get; set; }
        public int ShopNumber { get; set; }
        public int PayNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Pay Pay { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
