//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Suggest
    {
        [DisplayName("建議編號")]
        public int SuggestNumber { get; set; }

        [DisplayName("會員")]
        public int UserNumber { get; set; }

        [DisplayName("建議內容")]
        [Required(ErrorMessage = "請填寫建議內容")]
        public string Suggest1 { get; set; }

        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> SuggestDate { get; set; }

        [DisplayName("審閱日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> CheckDate { get; set; }

        [DisplayName("管理員")]
        public Nullable<int> AdmNumber { get; set; }
    
        public virtual Adm Adm { get; set; }
        public virtual Users Users { get; set; }
    }
}
