//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBlock
    {
        public int UserNumber { get; set; }
        public int AdmNumber { get; set; }
        public Nullable<System.DateTime> BlockDate { get; set; }
    
        public virtual Adm Adm { get; set; }
        public virtual Users Users { get; set; }
    }
}
