//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.PostShop = new HashSet<PostShop>();
            this.ShopImage = new HashSet<ShopImage>();
            this.ShopMenu = new HashSet<ShopMenu>();
            this.ShopTag = new HashSet<ShopTag>();
            this.Suggest = new HashSet<Suggest>();
        }

        [DisplayName("會員編號")]
        public int UserNumber { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號為必填")]
        public string UserAccount { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼為必填")]
        public string UserPassword { get; set; }

        [DisplayName("會員名稱")]
        [Required(ErrorMessage = "會員名稱為必填")]
        public string UserName { get; set; }

        [DisplayName("性別")]
        [Required(ErrorMessage = "性別為必填")]
        public bool Sex { get; set; }

        [DisplayName("照片")]
        public byte[] UserPhoto { get; set; }

        [DisplayName("生日")]
        [Required(ErrorMessage = "生日為必填")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Birthday { get; set; }

        [DisplayName("年齡")]
        public Nullable<int> Age { get; set; }

        [DisplayName("建立日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> UserDate { get; set; }

        [DisplayName("已封鎖")]
        //[DefaultValue(false)]
        public bool Blockade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostShop> PostShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopImage> ShopImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopMenu> ShopMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopTag> ShopTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suggest> Suggest { get; set; }
    }
}
